openapi: 3.2.0
info:
  title: Enterprise Documents TaxForms V2 API
  description: 'The Enterprise Document Service (EDS) API is the system of record for documents

    across the Zinnia life insurance and annuity platform.'
  version: 3.0.0
servers:
- url: https://dev.api.zinnia.io
  description: Dev Environment
- url: https://qa.api.zinnia.io
  description: QA Environment
- url: https://uat.api.zinnia.io
  description: UAT Environment
- url: https://api.zinnia.io
  description: PROD Environment
tags:
- name: TaxForms V2
  description: ''
paths:
  /document/v2/taxForms:
    get:
      operationId: getTaxForms-v2
      summary: Get tax forms v2
      description: This is an endpoint to get a list of tax-forms from SOVOS
      parameters:
      - name: Authorization
        required: true
        in: header
        example: Bearer <token>
        description: Authorization token
        schema:
          type: string
      - name: clientCode
        in: query
        example: EVGL
        description: Client code for the carrier/client
        schema:
          type: string
      - name: contractNumber
        required: true
        in: query
        description: Contract number for the document/tax-form
        example: '1234567898'
        schema:
          type: string
      - name: taxYear
        required: false
        in: query
        description: Tax-year for the form (defaults to current year-1)
        example: '2023'
        schema:
          type: string
      - name: numYears
        required: false
        in: query
        example: 1
        description: Number of years of forms to query in reverse chronological order from taxyear (incl). Min=1 and Max=5
        schema:
          minimum: 1
          maximum: 5
          default: 1
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxFormsResponse200'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse401'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse404'
      tags:
      - TaxForms V2
      security:
      - Auth0: []
      x-summary-source: derived
  /document/v2/taxForms/{formId}:
    get:
      operationId: downloadTaxForm-v2
      summary: Download tax form v2
      description: This is an endpoint to download a tax-form from SOVOS
      parameters:
      - name: Authorization
        required: true
        in: header
        example: Bearer <token>
        description: Authorization token
        schema:
          type: string
      - name: formId
        required: true
        in: path
        example: '123456'
        description: Form id for the tax-form
        schema:
          type: string
      - name: clientCode
        in: query
        example: EVGL
        description: Client code for the carrier/client
        schema:
          type: string
      - name: contractNumber
        required: true
        in: query
        example: '1234567898'
        description: Contract number for the document/tax-form
        schema:
          type: string
      - name: fChar
        required: true
        in: query
        example: R
        description: Unique string character associated with the tax-form name
        schema:
          type: string
      - name: taxYear
        required: false
        in: query
        example: '2023'
        description: Tax-year for the form (defaults to current year-1)
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadDocumentResponse'
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/DownloadDocumentResponse'
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse400'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse401'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineResponse404'
      tags:
      - TaxForms V2
      security:
      - Auth0: []
      x-summary-source: derived
components:
  schemas:
    InlineResponse404:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    InlineResponse400:
      type: object
      properties:
        xCorrelationId:
          type: string
        status:
          type: number
        errorDesc:
          type: string
        errorDetailedDesc:
          type: string
      required:
      - xCorrelationId
      - status
      - errorDesc
      - errorDetailedDesc
    InlineResponse401:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    TaxFormsResponse:
      type: object
      properties:
        contractNumber:
          type: string
          example: '1234567898'
          description: Contract number for the document/tax-form
        name:
          type: string
          example: 1099-R
          description: Name of the tax-form
        fChar:
          type: string
          example: R
          description: Unique string character associated with the tax-form name
        formId:
          type: string
          example: '123456'
          description: Form id for the tax-form
        taxYear:
          type: string
          example: '2023'
          description: Tax year for the tax-form
      required:
      - contractNumber
      - name
      - fChar
      - formId
      - taxYear
    TaxFormsResponse200:
      type: object
      properties:
        count:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/TaxFormsResponse'
      required:
      - count
      - items
    DownloadDocumentResponse:
      type: object
      properties:
        fileExtension:
          type: string
        binaryData:
          type: string
      required:
      - fileExtension
      - binaryData
  securitySchemes:
    basic:
      type: http
      scheme: basic
    Auth0:
      type: openIdConnect
      openIdConnectUrl: https://login.zinnia.com/.well-known/openid-configuration
      x-kong-security-openid-connect:
        config:
          run_on_preflight: true
          scopes_claim:
          - https://api.zinnia.io/permissions
          audience_claim:
          - aud
          audience_required:
          - https://api.zinnia.io
          client_id:
          - bGOIRPRq2ZnjCujDXC7ikwR5ez7VH5GZ
          auth_methods:
          - bearer
          scopes: []
        enabled: true
        protocols:
        - grpc
        - grpcs
        - http
        - https
